<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_work_with_us',
	'title' => 'Trabalhe Conosco',
	'fields' => array(
		// Accordion: Seção Principal
		array(
			'key' => 'field_wwu_section_accordion',
			'label' => 'Seção Principal',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_wwu_title',
			'label' => 'Título da Seção',
			'name' => 'wwu_title',
			'type' => 'text',
			'instructions' => 'Título principal da página (ex: Trabalhe Conosco)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Trabalhe Conosco',
			'maxlength' => '',
			'placeholder' => 'Trabalhe Conosco',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_wwu_description',
			'label' => 'Texto Descritivo',
			'name' => 'wwu_description',
			'type' => 'textarea',
			'instructions' => 'Texto de apresentação da página Trabalhe Conosco',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Na Zap Peças, acreditamos que o sucesso da nossa empresa está diretamente ligado ao talento e dedicação de nossa equipe. Se você está em busca de uma oportunidade em uma empresa que valoriza o desenvolvimento profissional, o trabalho em equipe e a paixão pelo setor automotivo, você está no lugar certo! Trabalhe conosco e faça parte de um time comprometido com a inovação e a qualidade de nossas peças.',
			'maxlength' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => 'br',
		),
		// Accordion: Redes Sociais
		array(
			'key' => 'field_wwu_social_accordion',
			'label' => 'Redes Sociais',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_wwu_social_title',
			'label' => 'Título Redes Sociais',
			'name' => 'wwu_social_title',
			'type' => 'text',
			'instructions' => 'Título da seção de redes sociais',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Redes Sociais',
			'maxlength' => '',
			'placeholder' => 'Redes Sociais',
			'prepend' => '',
			'append' => '',
		),
		// Accordion: Recursos Humanos
		array(
			'key' => 'field_wwu_hr_accordion',
			'label' => 'Recursos Humanos',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_wwu_hr_title',
			'label' => 'Título Recursos Humanos',
			'name' => 'wwu_hr_title',
			'type' => 'text',
			'instructions' => 'Título da seção de contato RH (ex: Recursos Humanos Zap Peças)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Recursos Humanos Zap Peças',
			'maxlength' => '',
			'placeholder' => 'Recursos Humanos Zap Peças',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_wwu_hr_email',
			'label' => 'E-mail Recursos Humanos',
			'name' => 'wwu_hr_email',
			'type' => 'email',
			'instructions' => 'E-mail do setor de Recursos Humanos',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'recursos.humanos@',
			'placeholder' => 'recursos.humanos@zappecas.com.br',
			'prepend' => '',
			'append' => '',
		),
		// Accordion: Endereço
		array(
			'key' => 'field_wwu_address_accordion',
			'label' => 'Endereço',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_wwu_address_title',
			'label' => 'Título Endereço',
			'name' => 'wwu_address_title',
			'type' => 'text',
			'instructions' => 'Título da seção de endereço',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Endereço',
			'maxlength' => '',
			'placeholder' => 'Endereço',
			'prepend' => '',
			'append' => '',
		),
		// Accordion: Formulário
		array(
			'key' => 'field_wwu_form_accordion',
			'label' => 'Formulário',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_wwu_form_file_label',
			'label' => 'Título do Campo Anexar Currículo',
			'name' => 'wwu_form_file_label',
			'type' => 'text',
			'instructions' => 'Título exibido acima do campo de upload de currículo no formulário',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Anexar Currículo',
			'maxlength' => '',
			'placeholder' => 'Anexar Currículo',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => get_page_by_path('trabalhe-conosco') ? get_page_by_path('trabalhe-conosco')->ID : 0,
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => 'Campos personalizados da página Trabalhe Conosco',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );
