<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_66f37003d0228',
	'title' => 'Representantes',
	'fields' => array(
		array(
			'key' => 'field_66f3700411978',
			'label' => 'Nome do Representante',
			'name' => 'nameRepresentant',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f37045e2fa2',
			'label' => 'Contato',
			'name' => 'contactRepresentant',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f37085e2fa3',
			'label' => 'E-mail',
			'name' => 'mailRepresentant',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66f370bea4e52',
			'label' => 'Cidade',
			'name' => 'cityRepresentant',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_67a1b2c3d4e5f',
			'label' => 'Região (somente São Paulo)',
			'name' => 'regiaoRepresentant',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Preencha apenas para representantes do estado de São Paulo.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66f5c9de717bc',
						'operator' => '==',
						'value' => 'brSP',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Capital'        => 'Capital',
				'Interior'       => 'Interior',
				'Vale do Paraíba' => 'Vale do Paraíba',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => 'Selecione a região',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_66f5c9de717bc',
			'label' => 'Estado do Representante',
			'name' => 'stateRepresentant',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'brAC' => 'Acre',
				'brAL' => 'Alagoas',
				'brAP' => 'Amapá',
				'brAM' => 'Amazonas',
				'brBA' => 'Bahia',
				'brCE' => 'Ceará',
				'brDF' => 'Distrito Federal',
				'brES' => 'Espírito Santo',
				'brGO' => 'Goiás',
				'brMA' => 'Maranhão',
				'brMT' => 'Mato Grosso',
				'brMS' => 'Mato Grosso do Sul',
				'brMG' => 'Minas Gerais',
				'brPA' => 'Pará',
				'brPB' => 'Paraíba',
				'brPR' => 'Paraná',
				'brPE' => 'Pernambuco',
				'brPI' => 'Piauí',
				'brRJ' => 'Rio de Janeiro',
				'brRN' => 'Rio Grande do Norte',
				'brRS' => 'Rio Grande do Sul',
				'brRO' => 'Rondônia',
				'brRR' => 'Roraima',
				'brSC' => 'Santa Catarina',
				'brSP' => 'São Paulo',
				'brSE' => 'Sergipe',
				'brTO' => 'Tocantins',
				'brEX' => 'Estrangeiro',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'create_options' => 0,
			'save_options' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'representante',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );

